#!/usr/bin/python3
# This code write by (Mr.nope)
import os
import time
class color:
    green = '\033[92m'
    red = '\033[91m'
    white = '\033[0m'
    blue = '\033[96m'
opt = color.green + "\nPTool/> " + color.white
def cls():
    os.system("clear")
def menu():
    cls()
    print(color.green + """
888888ba  d888888P                   dP
 88    `8b    88                      88
a88aaaa8P'    88    .d8888b. .d8888b. 88
 88           88    88'  `88 88'  `88 88 """ + color.red + " Version " + color.blue + "1.3.0" + color.green + """
 88           88    88.  .88 88.  .88 88
 dP           dP    `88888P' `88888P' dP

                                         """ + color.white)
    print("\n\t1.install package")
    print("\t2.update package")
    print("\t3.Help")
    print("\t4.Exit")
    choose = input(opt)
    if choose == '1':
      try_menu()
    elif choose == '2':
        menu3()
    elif choose == '3':
        cls()
        time.sleep(1)
        print("""
This code write by (Mr.nope)
usage:
     1 - Install pkg
     2 - update your system
     3 - Ptool Help
     4 - Exit package :(
""")
        time.sleep(1)
        try26 = input("\npress Enter... ")
        if try26 == '':
          menu()
        else:
            menu()
    elif choose == '4':
        ext()
    elif choose == '':
        menu()
    elif choose == ' ':
        menu()
    elif choose == '  ':
        menu()
    else:
        cls()
        print(choose + color.red + " Not Found!" + color.white)
        try_to_meinmenu()
def try_to_meinmenu():
    try8 = input("\npress Enter...")
    if try8 == '':
        menu()
    else:
        menu()
def try_menu():
    cls()
    print("\n1.Pkg Installing")
    print("2.Pkg Installing Menu")
    print("3.mein menu")
    choose4 = input(opt)
    if choose4 == '1':
        menu4()
    elif choose4 == '2':
        menu2()
    elif choose4 == '3':
        menu()
    else:
        try_menu()
def menu4():
    cls()
    pkgname = input("\nEnter pkg name: ")
    time.sleep(1)
    os.system("sudo apt install " + pkgname)
    try10()
def menu3():
    cls()
    print("\n1.Pkg Update")
    print("2.Bash Update")
    print("3.Bash Upgrade")
    print("4.mein menu")
    choose3 = input(opt)
    if choose3 == '1':
        cls()
        pkg = input("Enter pkg name: ")
        time.sleep(1)
        os.system("sudo apt remove " + pkg)
        os.system("sudo apt install " + pkg)
        try8 = input("\npress Enter...")
        if try8 == '':
            menu3()
        else:
            menu3()
    elif choose3 == '2':
        cls()
        os.system("sudo apt update")
        time.sleep(2)
        menu3()
    elif choose3 == '3':
        cls()
        os.system("sudo apt install upgrade")
        time.sleep(2)
        menu3()
    else:
        menu3()
def try10():
    try11 = input("\npress Enter...")
    if try11 == '':
        try_menu()
    else:
        try_menu()
def ext():
    cls()
    print(color.green + "Exiting...." + color.white)
    exit()
def menu2():
    cls()
    print("\n1.python")
    print("2.screenfetch")
    print("3.neofetch")
    print("4.tty-clock")
    print("5.cmatrix")
    print("6.htop")
    print("7.python")
    print("8.Fire-Fun")
    print("9.top")
    print("10.mein menu")
    choose2 = input(opt)
    if choose2 == '1':
      htool()
    elif choose2 == '2':
        os.system("sudo apt install screenfetch")
        try2 = input("\npress Enter...")
        if try2 == '':
          menu2()
        else:
            menu2()
    elif choose2 == '3':
        os.system("sudo apt install neofetch")
        try3 = input("\npress Enter...")
        if try3 == '':
            menu2()
        else:
            menu2()
    elif choose2 == '4':
        os.system("sudo apt install tty-clock")
        try4 = input("\npress Enter...")
        if try4 == '':
            menu2()
        else:
            menu2()
    elif choose2 == '5':
        os.system("sudo apt install cmatrox")
        try5 = input("\npress Enter...")
        if try5 == '':
            menu2()
        else:
            menu2()
    elif choose2 == '6':
        os.system("sudo apt install htop")
        try6 = input("\npress Enter...")
        if try6 == '':
            menu2()
        else:
            menu2()
    elif choose2 == '7':
        os.system("sudo apt install python")
        os.system("sudo apt install python3")
        try7 = input("\npress Enter...")
        if try7 == '':
          menu2()
        else:
            menu2()
    elif choose2 == '8':
        os.system("sudo apt install cacafire")
        try8 = input("\npress Enter...")
        if try8 == '':
            menu2()
        else:
            menu2()
    elif choose2 == '9':
        os.system("sudo apt install top")
        try9 = input("\npress Enter...")
        if try9 == '':
            meun2()
        else:
            menu2()
    elif choose2 == '10':
        menu()
    else:
        menu2()
if __name__ == '__main__':
    try:
        menu()
    except KeyboardInterrupt:
        print("\nCtrl + C")
        print("\nExiting...")
        exit()
