#!/usr/bin/bash
# This code write by Mr.nope
if [[ "$id -u" -ne 0 ]]; then
  echo "Please Run This Programm as Root!"
  exit 1
fi
clear
echo "Updating..."
sleep 2
cd .. && cd .. && rm -r Ptool && git clone https://github.com/mrprogrammer2938/PTool && cd PTool && bash install.sh
echo ""
echo "Updating..., Finish...!"
echo ""
exit 1
